

swagger:
  base-package: com.cxn.example.model.controller
  base-path: /**
  contact:
    email: 451624324@qq.com
    name: 陈湘宁
  description: Starter for swagger 2.x
  enabled: true
  title: 我的REST Api

spring:
  profiles:
    active: dev
