
my:
  a:
    title: 开发环境
    age: 20



spring:
  redis:
    database: 8
    database2: 2
    database3: 3
    host: 10.10.142.184
    password: 1qaz!QAZ
    pool:
      max-active: 80
      max-idle: 8
      max-wait: -1
      min-idle: 1
    port: 6379
